### ISSUE TITLE
Few common functions like setValue() does not work in Angular. 

### ISSUE THREAD

**Issue by eklavyalodha** [jspreadsheet/example-with-angular#6]
Thanks to JExcelTeam for great tool.

I am unable to use **setValue()** function in Angular. It would be great if you could provide an example(**preferably in online editor**) to that.
Note : Please not that getData(), getColumnNameFromId() etc. works perfectly fine in Angular.

**Comment by hodeware** [comment]
I imagine you have found the solution. Let me know if you need any further help.
